# Generated by Django 3.0.5 on 2020-05-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='isv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ISV'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
