# Generated by Django 3.0.5 on 2020-05-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20200507_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='proceso',
            field=models.IntegerField(choices=[(1, 'Compra'), (2, 'Finalizado')], default=1),
        ),
    ]
