# Generated by Django 3.0.5 on 2020-05-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_compras_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='multiplicador',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='Cuantas Unidades ?'),
            preserve_default=False,
        ),
    ]
