# Generated by Django 3.0.5 on 2020-05-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20200511_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='isv',
            field=models.DecimalField(decimal_places=2, max_digits=40, verbose_name='Isv'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=40, verbose_name='Total'),
        ),
    ]
