# Generated by Django 3.0.5 on 2020-05-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20200511_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='isv',
            field=models.FloatField(blank=True, null=True, verbose_name='ISV'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='subtotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='isv',
            field=models.FloatField(verbose_name='Isv'),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='total',
            field=models.FloatField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='isv',
            field=models.FloatField(blank=True, null=True, verbose_name='ISV'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='subtotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
