# Generated by Django 3.0.5 on 2020-05-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_auto_20200511_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='pre_compra',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precio Compra'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='pre_venta',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Precion Venta'),
        ),
    ]
