# Generated by Django 3.0.5 on 2020-05-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20200512_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventas',
            name='precio_c',
            field=models.FloatField(verbose_name='Precio Compra'),
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='precio_v',
            field=models.FloatField(verbose_name='Precio Venta'),
        ),
    ]
