# Generated by Django 3.0.5 on 2020-05-21 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0011_auto_20200515_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='multiplicador',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20, verbose_name='Cuantas Unidades ?'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='componente',
            name='stock_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Stock Inicial'),
        ),
        migrations.CreateModel(
            name='CuentasPorPagar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of Create')),
                ('date_change', models.DateField(auto_now=True, verbose_name='Date of Change')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('date_time_c', models.TimeField(auto_now_add=True)),
                ('date_time_m', models.TimeField(auto_now=True)),
                ('abono', models.FloatField(verbose_name='Abono')),
                ('comentario', models.TextField(blank=True, max_length=800, null=True, verbose_name='Comentario')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Cliente')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
