# Generated by Django 3.0.5 on 2020-05-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_auto_20200521_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='minimo_notificacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Notificar al Minimo'),
        ),
    ]
