# Generated by Django 3.0.5 on 2020-05-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_componente_minimo_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Activo para Ventas Online ?'),
        ),
    ]
