# Generated by Django 3.0.5 on 2020-05-29 02:17

import apps.control.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_componente_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to=apps.control.models.Componente_file),
        ),
        migrations.AddField(
            model_name='componente',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to=apps.control.models.Componente_file),
        ),
        migrations.AddField(
            model_name='componente',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to=apps.control.models.Componente_file),
        ),
        migrations.AddField(
            model_name='componente',
            name='imagen5',
            field=models.ImageField(blank=True, null=True, upload_to=apps.control.models.Componente_file),
        ),
        migrations.AddField(
            model_name='componente',
            name='imagen6',
            field=models.ImageField(blank=True, null=True, upload_to=apps.control.models.Componente_file),
        ),
    ]
