# Generated by Django 3.0.5 on 2020-05-31 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0016_auto_20200530_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=80, unique=True, verbose_name='Sub Categoria'),
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of Create')),
                ('date_change', models.DateField(auto_now=True, verbose_name='Date of Change')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('date_time_c', models.TimeField(auto_now_add=True)),
                ('date_time_m', models.TimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Talla')),
                ('descripcion', models.TextField(blank=True, max_length=600, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of Create')),
                ('date_change', models.DateField(auto_now=True, verbose_name='Date of Change')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('date_time_c', models.TimeField(auto_now_add=True)),
                ('date_time_m', models.TimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Color')),
                ('descripcion', models.TextField(blank=True, max_length=600, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='componente',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.Color'),
        ),
        migrations.AddField(
            model_name='componente',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.Talla'),
        ),
    ]
