# Generated by Django 3.0.5 on 2020-06-21 01:30

import apps.control.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0017_auto_20200530_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of Create')),
                ('date_change', models.DateField(auto_now=True, verbose_name='Date of Change')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('date_time_c', models.TimeField(auto_now_add=True)),
                ('date_time_m', models.TimeField(auto_now=True)),
                ('codigo', models.CharField(default=apps.control.models.code_carrito, max_length=60, unique=True, verbose_name='Codigo')),
                ('pago', models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Tarjeta')], default=1)),
                ('isv', models.FloatField(blank=True, null=True, verbose_name='ISV')),
                ('comentarios', models.TextField(blank=True, max_length=1800, null=True, verbose_name='Comentarios')),
                ('subtotal', models.FloatField(blank=True, null=True, verbose_name='Sub Total')),
                ('total', models.FloatField(blank=True, null=True, verbose_name='Total')),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='control.Cliente')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detalle_envio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of Create')),
                ('date_change', models.DateField(auto_now=True, verbose_name='Date of Change')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('date_time_c', models.TimeField(auto_now_add=True)),
                ('date_time_m', models.TimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo ')),
                ('telefono', models.CharField(max_length=11, verbose_name='Telefono')),
                ('telefono2', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefono (Opcional)')),
                ('direccion', models.TextField(max_length=600, verbose_name='Direccion')),
                ('direccion2', models.TextField(blank=True, max_length=600, null=True, verbose_name='Direccion (Opcional)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Carrito')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detalle_Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Date of Create')),
                ('date_change', models.DateField(auto_now=True, verbose_name='Date of Change')),
                ('date_delete', models.DateField(auto_now=True, verbose_name='Date of Delete')),
                ('date_time_c', models.TimeField(auto_now_add=True)),
                ('date_time_m', models.TimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cantidad')),
                ('precio_c', models.FloatField(verbose_name='Precio Compra')),
                ('precio_v', models.FloatField(verbose_name='Precio Venta')),
                ('isv', models.FloatField(verbose_name='Isv')),
                ('total', models.FloatField(verbose_name='Total')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Carrito')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Componente')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
