# Generated by Django 3.0.5 on 2020-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_auto_20200620_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Compra Iniciada'), (2, 'Confimacion de Compra'), (3, 'Proceso de envio'), (4, 'Entregado')], default=1),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='pago',
            field=models.IntegerField(choices=[(1, 'Pagar al Entregar'), (2, 'Tigo Money'), (3, 'Transferencia Bancaria'), (4, 'Paypal')], default=1),
        ),
    ]
